-- Superseded within the same session by
-- 20260731092702_migrate_loan_live_photo_sentinel.sql, which carries the
-- definitive CREATE OR REPLACE for app.migrate_loan.
--
-- Recorded here because the ledger has this version and files must match
-- it one-for-one. The fix this step made is described below; replaying
-- 092315 -> 092702 in order produces the same final function either way,
-- since every step was a full CREATE OR REPLACE of the same function.
--
-- FIX: CASE ... END yields text, but loans.loan_status is loan_status_enum.
-- plpgsql does not type-check statements at CREATE time, so the original
-- applied cleanly and failed on the first call. Added an explicit
-- ::loan_status_enum cast via a typed local.
